from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(332, 445)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 301, 421))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 231, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.dobavitclienta = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.dobavitclienta.setContentsMargins(0, 0, 0, 0)
        self.dobavitclienta.setObjectName("dobavitclienta")
        self.f_name = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.f_name.setObjectName("f_name")
        self.dobavitclienta.addWidget(self.f_name)
        self.l_name = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.l_name.setObjectName("l_name")
        self.dobavitclienta.addWidget(self.l_name)
        self.dateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dateEdit.setObjectName("dateEdit")
        self.dobavitclienta.addWidget(self.dateEdit)
        self.phone = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.phone.setObjectName("phone")
        self.dobavitclienta.addWidget(self.phone)
        self.email = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.email.setObjectName("email")
        self.dobavitclienta.addWidget(self.email)
        self.adress = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.adress.setObjectName("adress")
        self.dobavitclienta.addWidget(self.adress)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 370, 231, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.redactirovatclients = QtWidgets.QComboBox(self.page_2)
        self.redactirovatclients.setGeometry(QtCore.QRect(10, 0, 231, 31))
        self.redactirovatclients.setObjectName("redactirovatclients")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.page_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 40, 231, 291))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.redactirovatclienta = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.redactirovatclienta.setContentsMargins(0, 0, 0, 0)
        self.redactirovatclienta.setObjectName("redactirovatclienta")
        self.f_name_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.f_name_2.setObjectName("f_name_2")
        self.redactirovatclienta.addWidget(self.f_name_2)
        self.l_name_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.l_name_2.setObjectName("l_name_2")
        self.redactirovatclienta.addWidget(self.l_name_2)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.verticalLayoutWidget_3)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.redactirovatclienta.addWidget(self.dateEdit_2)
        self.phone_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.phone_2.setObjectName("phone_2")
        self.redactirovatclienta.addWidget(self.phone_2)
        self.email_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.email_2.setObjectName("email_2")
        self.redactirovatclienta.addWidget(self.email_2)
        self.adress_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.adress_2.setObjectName("adress_2")
        self.redactirovatclienta.addWidget(self.adress_2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 380, 231, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.redactirovatclients_2 = QtWidgets.QComboBox(self.page_3)
        self.redactirovatclients_2.setGeometry(QtCore.QRect(10, 10, 231, 31))
        self.redactirovatclients_2.setObjectName("redactirovatclients_2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.page_3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 50, 231, 291))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.deletetheclient = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.deletetheclient.setContentsMargins(0, 0, 0, 0)
        self.deletetheclient.setObjectName("deletetheclient")
        self.f_name_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.f_name_3.setObjectName("f_name_3")
        self.deletetheclient.addWidget(self.f_name_3)
        self.l_name_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.l_name_3.setObjectName("l_name_3")
        self.deletetheclient.addWidget(self.l_name_3)
        self.dateEdit_3 = QtWidgets.QDateEdit(self.verticalLayoutWidget_4)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.deletetheclient.addWidget(self.dateEdit_3)
        self.phone_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.phone_3.setObjectName("phone_3")
        self.deletetheclient.addWidget(self.phone_3)
        self.email_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.email_3.setObjectName("email_3")
        self.deletetheclient.addWidget(self.email_3)
        self.adress_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.adress_3.setObjectName("adress_3")
        self.deletetheclient.addWidget(self.adress_3)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.page_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 370, 241, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.deleteclient = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.deleteclient.setObjectName("deleteclient")
        self.horizontalLayout_3.addWidget(self.deleteclient)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.client = QtWidgets.QComboBox(self.page_4)
        self.client.setGeometry(QtCore.QRect(10, 10, 171, 31))
        self.client.setObjectName("client")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.page_4)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 380, 195, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_4.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_4.addWidget(self.pushButton_8)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 171, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.dobavit_account = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.dobavit_account.setContentsMargins(0, 0, 0, 0)
        self.dobavit_account.setObjectName("dobavit_account")
        self.account_type = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.account_type.setObjectName("account_type")
        self.dobavit_account.addWidget(self.account_type)
        self.currency_type = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.currency_type.setObjectName("currency_type")
        self.dobavit_account.addWidget(self.currency_type)
        self.balance_currency = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.balance_currency.setObjectName("balance_currency")
        self.dobavit_account.addWidget(self.balance_currency)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.vibor_client = QtWidgets.QComboBox(self.page_5)
        self.vibor_client.setGeometry(QtCore.QRect(10, 20, 171, 31))
        self.vibor_client.setObjectName("vibor_client")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.page_5)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 360, 195, 51))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_9 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_5.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_5.addWidget(self.pushButton_10)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.page_5)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 110, 171, 151))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.redactirovat_account = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.redactirovat_account.setContentsMargins(0, 0, 0, 0)
        self.redactirovat_account.setObjectName("redactirovat_account")
        self.account_type_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.account_type_2.setObjectName("account_type_2")
        self.redactirovat_account.addWidget(self.account_type_2)
        self.currency_type_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.currency_type_2.setObjectName("currency_type_2")
        self.redactirovat_account.addWidget(self.currency_type_2)
        self.balance_currency_2 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_5)
        self.balance_currency_2.setObjectName("balance_currency_2")
        self.redactirovat_account.addWidget(self.balance_currency_2)
        self.vibor_account_ = QtWidgets.QComboBox(self.page_5)
        self.vibor_account_.setGeometry(QtCore.QRect(10, 60, 171, 31))
        self.vibor_account_.setObjectName("vibor_account_")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.vibor_account_3 = QtWidgets.QComboBox(self.page_6)
        self.vibor_account_3.setGeometry(QtCore.QRect(10, 10, 171, 31))
        self.vibor_account_3.setObjectName("vibor_account_3")
        self.vibor_account_4 = QtWidgets.QComboBox(self.page_6)
        self.vibor_account_4.setGeometry(QtCore.QRect(10, 50, 171, 31))
        self.vibor_account_4.setObjectName("vibor_account_4")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.page_6)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 90, 171, 151))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.close_theaccount = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.close_theaccount.setContentsMargins(0, 0, 0, 0)
        self.close_theaccount.setObjectName("close_theaccount")
        self.account_type_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.account_type_3.setObjectName("account_type_3")
        self.close_theaccount.addWidget(self.account_type_3)
        self.currency_type_3 = QtWidgets.QComboBox(self.verticalLayoutWidget_6)
        self.currency_type_3.setObjectName("currency_type_3")
        self.close_theaccount.addWidget(self.currency_type_3)
        self.balance_currency_3 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_6)
        self.balance_currency_3.setObjectName("balance_currency_3")
        self.close_theaccount.addWidget(self.balance_currency_3)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.page_6)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(0, 360, 201, 51))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_13 = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_6.addWidget(self.pushButton_13)
        self.pushButton_12 = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_6.addWidget(self.pushButton_12)
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.transactions_create = QtWidgets.QComboBox(self.page_7)
        self.transactions_create.setGeometry(QtCore.QRect(10, 20, 191, 31))
        self.transactions_create.setObjectName("transactions_create")
        self.vibor_account_6 = QtWidgets.QComboBox(self.page_7)
        self.vibor_account_6.setGeometry(QtCore.QRect(10, 60, 191, 31))
        self.vibor_account_6.setObjectName("vibor_account_6")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.page_7)
        self.doubleSpinBox.setGeometry(QtCore.QRect(10, 100, 191, 31))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.textEdit = QtWidgets.QTextEdit(self.page_7)
        self.textEdit.setGeometry(QtCore.QRect(10, 140, 191, 81))
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.page_7)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(0, 360, 201, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_14 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_7.addWidget(self.pushButton_14)
        self.pushButton_11 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_7.addWidget(self.pushButton_11)
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.find_the_transaction = QtWidgets.QComboBox(self.page_8)
        self.find_the_transaction.setGeometry(QtCore.QRect(10, 10, 191, 31))
        self.find_the_transaction.setObjectName("find_the_transaction")
        self.dateEdit_4 = QtWidgets.QDateEdit(self.page_8)
        self.dateEdit_4.setGeometry(QtCore.QRect(10, 50, 191, 31))
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.page_8)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(0, 360, 244, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_8.addWidget(self.pushButton_5)
        self.pushButton_16 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_8.addWidget(self.pushButton_16)
        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.creditcreate = QtWidgets.QComboBox(self.page_9)
        self.creditcreate.setGeometry(QtCore.QRect(10, 10, 191, 31))
        self.creditcreate.setObjectName("creditcreate")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.page_9)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(10, 50, 191, 31))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.creditcreate_2 = QtWidgets.QComboBox(self.page_9)
        self.creditcreate_2.setGeometry(QtCore.QRect(10, 90, 191, 31))
        self.creditcreate_2.setObjectName("creditcreate_2")
        self.start_credit = QtWidgets.QDateEdit(self.page_9)
        self.start_credit.setGeometry(QtCore.QRect(10, 130, 191, 31))
        self.start_credit.setObjectName("start_credit")
        self.end_credit = QtWidgets.QDateEdit(self.page_9)
        self.end_credit.setGeometry(QtCore.QRect(10, 170, 191, 31))
        self.end_credit.setObjectName("end_credit")
        self.percent_stage = QtWidgets.QDoubleSpinBox(self.page_9)
        self.percent_stage.setGeometry(QtCore.QRect(10, 210, 191, 31))
        self.percent_stage.setObjectName("percent_stage")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.page_9)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(0, 370, 232, 41))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_15 = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_9.addWidget(self.pushButton_15)
        self.pushButton_17 = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_9.addWidget(self.pushButton_17)
        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.vibor_client_2 = QtWidgets.QComboBox(self.page_10)
        self.vibor_client_2.setGeometry(QtCore.QRect(10, 10, 191, 31))
        self.vibor_client_2.setObjectName("vibor_client_2")
        self.vibor_credit = QtWidgets.QComboBox(self.page_10)
        self.vibor_credit.setGeometry(QtCore.QRect(10, 50, 191, 31))
        self.vibor_credit.setObjectName("vibor_credit")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.page_10)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(10, 90, 191, 31))
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.start_credit_2 = QtWidgets.QDateEdit(self.page_10)
        self.start_credit_2.setGeometry(QtCore.QRect(10, 130, 191, 31))
        self.start_credit_2.setObjectName("start_credit_2")
        self.start_credit_3 = QtWidgets.QDateEdit(self.page_10)
        self.start_credit_3.setGeometry(QtCore.QRect(10, 170, 191, 31))
        self.start_credit_3.setObjectName("start_credit_3")
        self.percent_stage_2 = QtWidgets.QDoubleSpinBox(self.page_10)
        self.percent_stage_2.setGeometry(QtCore.QRect(10, 210, 191, 31))
        self.percent_stage_2.setObjectName("percent_stage_2")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.page_10)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(10, 370, 195, 41))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_18 = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_10.addWidget(self.pushButton_18)
        self.pushButton_19 = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_10.addWidget(self.pushButton_19)
        self.stackedWidget.addWidget(self.page_10)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.vibor_client_3 = QtWidgets.QComboBox(self.page_11)
        self.vibor_client_3.setGeometry(QtCore.QRect(10, 10, 191, 31))
        self.vibor_client_3.setObjectName("vibor_client_3")
        self.vibor_client_4 = QtWidgets.QComboBox(self.page_11)
        self.vibor_client_4.setGeometry(QtCore.QRect(10, 50, 191, 31))
        self.vibor_client_4.setObjectName("vibor_client_4")
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.page_11)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(0, 380, 219, 41))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_20 = QtWidgets.QPushButton(self.horizontalLayoutWidget_11)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_11.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.horizontalLayoutWidget_11)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_11.addWidget(self.pushButton_21)
        self.stackedWidget.addWidget(self.page_11)
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.vibor_client_5 = QtWidgets.QComboBox(self.page_12)
        self.vibor_client_5.setGeometry(QtCore.QRect(10, 10, 191, 31))
        self.vibor_client_5.setObjectName("vibor_client_5")
        self.lineEdit = QtWidgets.QLineEdit(self.page_12)
        self.lineEdit.setGeometry(QtCore.QRect(10, 50, 191, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.dateEdit_5 = QtWidgets.QDateEdit(self.page_12)
        self.dateEdit_5.setGeometry(QtCore.QRect(10, 90, 191, 31))
        self.dateEdit_5.setObjectName("dateEdit_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_12)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 130, 191, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.page_12)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(0, 370, 201, 51))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_22 = QtWidgets.QPushButton(self.horizontalLayoutWidget_12)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_12.addWidget(self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(self.horizontalLayoutWidget_12)
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_12.addWidget(self.pushButton_23)
        self.stackedWidget.addWidget(self.page_12)
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setObjectName("page_13")
        self.vibor_client_6 = QtWidgets.QComboBox(self.page_13)
        self.vibor_client_6.setGeometry(QtCore.QRect(10, 10, 191, 31))
        self.vibor_client_6.setObjectName("vibor_client_6")
        self.vibor_client_7 = QtWidgets.QComboBox(self.page_13)
        self.vibor_client_7.setGeometry(QtCore.QRect(10, 50, 191, 31))
        self.vibor_client_7.setObjectName("vibor_client_7")
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self.page_13)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(0, 380, 201, 41))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_24 = QtWidgets.QPushButton(self.horizontalLayoutWidget_13)
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_13.addWidget(self.pushButton_24)
        self.pushButton_26 = QtWidgets.QPushButton(self.horizontalLayoutWidget_13)
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_13.addWidget(self.pushButton_26)
        self.stackedWidget.addWidget(self.page_13)
        self.page_14 = QtWidgets.QWidget()
        self.page_14.setObjectName("page_14")
        self.vibor_client_8 = QtWidgets.QComboBox(self.page_14)
        self.vibor_client_8.setGeometry(QtCore.QRect(10, 10, 191, 31))
        self.vibor_client_8.setObjectName("vibor_client_8")
        self.horizontalLayoutWidget_14 = QtWidgets.QWidget(self.page_14)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(0, 370, 201, 41))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_25 = QtWidgets.QPushButton(self.horizontalLayoutWidget_14)
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_14.addWidget(self.pushButton_25)
        self.pushButton_27 = QtWidgets.QPushButton(self.horizontalLayoutWidget_14)
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_14.addWidget(self.pushButton_27)
        self.stackedWidget.addWidget(self.page_14)
        self.page_15 = QtWidgets.QWidget()
        self.page_15.setObjectName("page_15")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_15)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 10, 191, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.vibor_client_9 = QtWidgets.QComboBox(self.page_15)
        self.vibor_client_9.setGeometry(QtCore.QRect(10, 50, 191, 31))
        self.vibor_client_9.setObjectName("vibor_client_9")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_15)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 90, 191, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.page_15)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 130, 191, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayoutWidget_15 = QtWidgets.QWidget(self.page_15)
        self.horizontalLayoutWidget_15.setGeometry(QtCore.QRect(0, 370, 201, 41))
        self.horizontalLayoutWidget_15.setObjectName("horizontalLayoutWidget_15")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_15)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_28 = QtWidgets.QPushButton(self.horizontalLayoutWidget_15)
        self.pushButton_28.setObjectName("pushButton_28")
        self.horizontalLayout_15.addWidget(self.pushButton_28)
        self.pushButton_29 = QtWidgets.QPushButton(self.horizontalLayoutWidget_15)
        self.pushButton_29.setObjectName("pushButton_29")
        self.horizontalLayout_15.addWidget(self.pushButton_29)
        self.stackedWidget.addWidget(self.page_15)
        self.page_16 = QtWidgets.QWidget()
        self.page_16.setObjectName("page_16")
        self.vibor_client_10 = QtWidgets.QComboBox(self.page_16)
        self.vibor_client_10.setGeometry(QtCore.QRect(10, 10, 191, 31))
        self.vibor_client_10.setObjectName("vibor_client_10")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.page_16)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 50, 191, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.page_16)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 90, 191, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.vibor_client_11 = QtWidgets.QComboBox(self.page_16)
        self.vibor_client_11.setGeometry(QtCore.QRect(10, 130, 191, 31))
        self.vibor_client_11.setObjectName("vibor_client_11")
        self.vibor_client_12 = QtWidgets.QComboBox(self.page_16)
        self.vibor_client_12.setGeometry(QtCore.QRect(10, 170, 191, 31))
        self.vibor_client_12.setObjectName("vibor_client_12")
        self.horizontalLayoutWidget_16 = QtWidgets.QWidget(self.page_16)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(0, 370, 201, 41))
        self.horizontalLayoutWidget_16.setObjectName("horizontalLayoutWidget_16")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_30 = QtWidgets.QPushButton(self.horizontalLayoutWidget_16)
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout_16.addWidget(self.pushButton_30)
        self.pushButton_31 = QtWidgets.QPushButton(self.horizontalLayoutWidget_16)
        self.pushButton_31.setObjectName("pushButton_31")
        self.horizontalLayout_16.addWidget(self.pushButton_31)
        self.stackedWidget.addWidget(self.page_16)
        self.page_17 = QtWidgets.QWidget()
        self.page_17.setObjectName("page_17")
        self.vibor_client_13 = QtWidgets.QComboBox(self.page_17)
        self.vibor_client_13.setGeometry(QtCore.QRect(10, 10, 191, 31))
        self.vibor_client_13.setObjectName("vibor_client_13")
        self.vibor_client_14 = QtWidgets.QComboBox(self.page_17)
        self.vibor_client_14.setGeometry(QtCore.QRect(10, 50, 191, 31))
        self.vibor_client_14.setObjectName("vibor_client_14")
        self.horizontalLayoutWidget_17 = QtWidgets.QWidget(self.page_17)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(0, 380, 201, 41))
        self.horizontalLayoutWidget_17.setObjectName("horizontalLayoutWidget_17")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_32 = QtWidgets.QPushButton(self.horizontalLayoutWidget_17)
        self.pushButton_32.setObjectName("pushButton_32")
        self.horizontalLayout_17.addWidget(self.pushButton_32)
        self.pushButton_33 = QtWidgets.QPushButton(self.horizontalLayoutWidget_17)
        self.pushButton_33.setObjectName("pushButton_33")
        self.horizontalLayout_17.addWidget(self.pushButton_33)
        self.stackedWidget.addWidget(self.page_17)
        self.page_18 = QtWidgets.QWidget()
        self.page_18.setObjectName("page_18")
        self.horizontalLayoutWidget_18 = QtWidgets.QWidget(self.page_18)
        self.horizontalLayoutWidget_18.setGeometry(QtCore.QRect(10, 370, 201, 41))
        self.horizontalLayoutWidget_18.setObjectName("horizontalLayoutWidget_18")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_18)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButton_34 = QtWidgets.QPushButton(self.horizontalLayoutWidget_18)
        self.pushButton_34.setObjectName("pushButton_34")
        self.horizontalLayout_18.addWidget(self.pushButton_34)
        self.pushButton_35 = QtWidgets.QPushButton(self.horizontalLayoutWidget_18)
        self.pushButton_35.setObjectName("pushButton_35")
        self.horizontalLayout_18.addWidget(self.pushButton_35)
        self.vibor_client_15 = QtWidgets.QComboBox(self.page_18)
        self.vibor_client_15.setGeometry(QtCore.QRect(10, 10, 191, 31))
        self.vibor_client_15.setObjectName("vibor_client_15")
        self.vibor_client_16 = QtWidgets.QComboBox(self.page_18)
        self.vibor_client_16.setGeometry(QtCore.QRect(10, 50, 191, 31))
        self.vibor_client_16.setObjectName("vibor_client_16")
        self.stackedWidget.addWidget(self.page_18)
        self.page_19 = QtWidgets.QWidget()
        self.page_19.setObjectName("page_19")
        self.vibor_client_17 = QtWidgets.QComboBox(self.page_19)
        self.vibor_client_17.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        self.vibor_client_17.setFont(font)
        self.vibor_client_17.setObjectName("vibor_client_17")
        self.vibor_client_18 = QtWidgets.QComboBox(self.page_19)
        self.vibor_client_18.setGeometry(QtCore.QRect(10, 50, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        self.vibor_client_18.setFont(font)
        self.vibor_client_18.setObjectName("vibor_client_18")
        self.dateEdit_6 = QtWidgets.QDateEdit(self.page_19)
        self.dateEdit_6.setGeometry(QtCore.QRect(10, 90, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        self.dateEdit_6.setFont(font)
        self.dateEdit_6.setObjectName("dateEdit_6")
        self.dateEdit_7 = QtWidgets.QDateEdit(self.page_19)
        self.dateEdit_7.setGeometry(QtCore.QRect(10, 130, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        self.dateEdit_7.setFont(font)
        self.dateEdit_7.setObjectName("dateEdit_7")
        self.horizontalLayoutWidget_19 = QtWidgets.QWidget(self.page_19)
        self.horizontalLayoutWidget_19.setGeometry(QtCore.QRect(0, 370, 201, 41))
        self.horizontalLayoutWidget_19.setObjectName("horizontalLayoutWidget_19")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_19)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButton_36 = QtWidgets.QPushButton(self.horizontalLayoutWidget_19)
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        self.pushButton_36.setFont(font)
        self.pushButton_36.setObjectName("pushButton_36")
        self.horizontalLayout_19.addWidget(self.pushButton_36)
        self.pushButton_37 = QtWidgets.QPushButton(self.horizontalLayoutWidget_19)
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        self.pushButton_37.setFont(font)
        self.pushButton_37.setObjectName("pushButton_37")
        self.horizontalLayout_19.addWidget(self.pushButton_37)
        self.stackedWidget.addWidget(self.page_19)
        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(8)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "OK"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
        self.pushButton_3.setText(_translate("Dialog", "OK"))
        self.pushButton_4.setText(_translate("Dialog", "Cancel"))
        self.deleteclient.setText(_translate("Dialog", "Удалить клиента"))
        self.pushButton_6.setText(_translate("Dialog", "Cancel"))
        self.pushButton_7.setText(_translate("Dialog", "OK"))
        self.pushButton_8.setText(_translate("Dialog", "Cancel"))
        self.pushButton_9.setText(_translate("Dialog", "OK"))
        self.pushButton_10.setText(_translate("Dialog", "Cancel"))
        self.pushButton_13.setText(_translate("Dialog", "Закрыть счет"))
        self.pushButton_12.setText(_translate("Dialog", "Cancel"))
        self.pushButton_14.setText(_translate("Dialog", "Создать "))
        self.pushButton_11.setText(_translate("Dialog", "Cancel"))
        self.pushButton_5.setText(_translate("Dialog", "Найти транзакцию"))
        self.pushButton_16.setText(_translate("Dialog", "Cancel"))
        self.pushButton_15.setText(_translate("Dialog", "Оформить кредит"))
        self.pushButton_17.setText(_translate("Dialog", "Cancel"))
        self.pushButton_18.setText(_translate("Dialog", "OK"))
        self.pushButton_19.setText(_translate("Dialog", "Cancel"))
        self.pushButton_20.setText(_translate("Dialog", "Закрыть кредит"))
        self.pushButton_21.setText(_translate("Dialog", "Cancel"))
        self.pushButton_22.setText(_translate("Dialog", "ОК"))
        self.pushButton_23.setText(_translate("Dialog", "Cancel"))
        self.pushButton_24.setText(_translate("Dialog", "Привязать"))
        self.pushButton_26.setText(_translate("Dialog", "Cancel"))
        self.pushButton_25.setText(_translate("Dialog", "Удалить"))
        self.pushButton_27.setText(_translate("Dialog", "Cancel"))
        self.pushButton_28.setText(_translate("Dialog", "ОК"))
        self.pushButton_29.setText(_translate("Dialog", "Cancel"))
        self.pushButton_30.setText(_translate("Dialog", "ОК"))
        self.pushButton_31.setText(_translate("Dialog", "Cancel"))
        self.pushButton_32.setText(_translate("Dialog", "ОК"))
        self.pushButton_33.setText(_translate("Dialog", "Cancel"))
        self.pushButton_34.setText(_translate("Dialog", "Назначить"))
        self.pushButton_35.setText(_translate("Dialog", "Cancel"))
        self.pushButton_36.setText(_translate("Dialog", "Поиск"))
        self.pushButton_37.setText(_translate("Dialog", "Cancel"))